[versions]
spock = "2.4-groovy-5.0-SNAPSHOT"
junit = "5.+"
byteBuddy = "1.+"

[libraries]
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatform = { module = "org.junit.platform:junit-platform-launcher" }
byteBuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byteBuddy" }

[bundles]
test = ["spock", "junit", "byteBuddy"]
testRuntime = ["junitPlatform"]
